### ISSUE TITLE
[Improvement] JSExportedDartFunction lacks argument and return types by default

### ISSUE THREAD

**Issue by AlexDochioiu** [dart-lang/web#215] opened 2024-03-27 20:34 UTC
I personally found `JSExportedDartFunction` to be a big step down compared to `allowInterop()` because it loses the return type as well as expected argument(s) and their types. While I like the compile-time check for the function to be callable in js, I'm not a fan of losing types/etc.

I did however create my own hack/solution to bring types back. I think it may be worth considering adding it directly as part of the `web` or `js_interop` library.

```dart
import 'dart:js_interop';

extension type JSExportedDartTypedFunction0<OUT extends JSAny?>(JSExportedDartFunction _) {}

extension type JSExportedDartTypedFunction1<OUT extends JSAny?, ARG1 extends JSAny?>(JSExportedDartFunction _) {}

extension type JSExportedDartTypedFunction2<OUT extends JSAny?, ARG1 extends JSAny?, ARG2 extends JSAny?>(
    JSExportedDartFunction _) {}

extension Js0X<OUT extends JSAny?> on OUT Function() {
  JSExportedDartTypedFunction0<OUT> get toTypedJS => JSExportedDartTypedFunction0<OUT>(toJS);
}

extension Js1X<OUT extends JSAny?, ARG1 extends JSAny?> on OUT Function(ARG1) {
  JSExportedDartTypedFunction1<OUT, ARG1> get toTypedJS => JSExportedDartTypedFunction1<OUT, ARG1>(toJS);
}

extension Js2X<OUT extends JSAny?, ARG1 extends JSAny?, ARG2 extends JSAny?> on OUT Function(ARG1, ARG2) {
  JSExportedDartTypedFunction2<OUT, ARG1, ARG2> get toTypedJS => JSExportedDartTypedFunction2<OUT, ARG1, ARG2>(toJS);
}
```

And then I use it like this:
```dart
extension type ChromeSidePanelApi._(JSObject _) implements JSObject {
  @JS('open')
  external void _open(OpenOptions options, [JSExportedDartTypedFunction0<Null>? callback]);
  @JS('setOptions')
  external void _setOptions(PanelOptions options, [JSExportedDartTypedFunction0<Null>? callback]);
  @JS('getOptions')
  external void _getOptions(GetPanelOptions options, [JSExportedDartTypedFunction1<Null, PanelOptions>? callback]);

  void open(OpenOptions options, [Null Function()? callback]) => _open(options, callback?.toTypedJS);
  void setOptions(PanelOptions options, [Null Function()? callback]) => _setOptions(options, callback?.toTypedJS);
  void getOptions(GetPanelOptions options, [Null Function(PanelOptions options)? callback]) =>
      _getOptions(options, callback?.toTypedJS);
}
```

**Comment by AlexDochioiu** [comment] 2024-03-27 20:36
P.s. I guess the `extension type`s added can also include `toTypedDart` for the inverse conversion.

**Comment by srujzs** [comment] 2024-04-02 16:03
Similar issue here: https://github.com/dart-lang/sdk/issues/54557, although that issue uses a singular function type to capture static type information.

It affecting `JSExportedDartFunction` on not `JSFunction` does come with a downside though. If we were to migrate `package:web` to the former, that essentially means you shouldn't pass functions that originated in JS to `package:web` APIs. We could also make `JSFunction` generic, but what that means it isn't clear since JS functions don't have a Dart type if they didn't originate in Dart. Of course, casting stuff makes it work well enough since extension type args are erased.

There's also the breaking change element of this, but that could be better mitigated.

**Comment by srujzs** [comment] 2024-04-02 16:04
Duplicate of https://github.com/dart-lang/sdk/issues/54557.

**Closed by srujzs** 2024-04-02 16:04 UTC
