### ISSUE TITLE
 Error: The argument type 'HTMLStyleElement' can't be assigned to the parameter type 'JSAny'.

### ISSUE THREAD

**Issue by dimiril** [dart-lang/web#129] opened 2023-12-23 21:33 UTC
```
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
../../../flutter/packages/flutter/lib/src/widgets/_platform_selectable_region_context_menu_web.dart:118:33: Error: The argument type 'HTMLStyleElement' can't be assigned to the parameter type 'JSAny'.

'HTMLStyleElement' is from 'package:web/src/dom/html.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.4.0/lib/src/dom/html.dart').
'JSAny' is from 'dart:_js_types'.
web.document.head!.append(styleElement);
^
Failed to compile application.
```

**Comment by bsz0206** [comment] 2024-01-04 07:13
I get the same error on 0.4.0 and not 0.3.0. 

0      RunResult.throwException (package:flutter_tools/src/base/process.dart:127:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:280:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:189:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:89:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:199:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

**Comment by srujzs** [comment] 2024-01-09 01:02
Duplicate of https://github.com/dart-lang/web/issues/128. The resolution is to pin the version e.g. `web: 0.3.0` as Flutter pins the version.

**Closed by srujzs** 2024-01-09 01:02 UTC

**Comment by bsz0206** [comment] 2024-01-09 01:21
@srujzs how about a long term solution?
