### ISSUE TITLE
DataTransferItemList is missing indexer / can't get items

### ISSUE THREAD

**Issue by jezell** [dart-lang/web#270] opened 2024-07-02 22:44 UTC
```dart

external DataTransferItem operator [](int index);

```

https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItemList

**Comment by srujzs** [comment] 2024-07-08 23:29
Duplicate of https://github.com/dart-lang/web/issues/127

**Closed** 2024-09-25 20:39 UTC
Labels: area-api-bug
