### ISSUE TITLE
HTMLMetaElement throw TypeError: Illegal constructor

### ISSUE THREAD

**Issue by amrgetment** [dart-lang/web#183] opened 2024-02-21 12:39 UTC
In Flutter 3.19 I tried web 0.4.2 and I got the following error `TypeError: Illegal constructor`
when I used HTMLMetaElement

```
  final HTMLMetaElement metaElement = HTMLMetaElement()
    ..name = 'google-signin-client_id'
    ..content = flavor.googleWebClientId;

```
similar issues:
https://github.com/dart-lang/web/issues/124
https://github.com/flutter/flutter/issues/139125

**Comment by srujzs** [comment] 2024-02-21 17:18
This is actually a duplicate of https://github.com/dart-lang/web/issues/53 and not the other issue - the way to instantiate `Element`s is `document.createElement(<name_of_element_tag>)` e.g. `document.createElement('meta')`. There's a different request to autogenerate such syntax (or stop generating `Element` constructors since they're broken) for each `Element`, and that'll likely be the solution for #53.

**Closed by srujzs** 2024-02-21 17:18 UTC

**Comment by kevmoo** [comment] 2024-02-22 16:01
@amrgetment – the decision is to just ship what the standard IDL gives us (for now). We have a BUNCH of extra stuff in `dart:html` to make things easier. We're going slow adding these helpers and extra things to `pkg:web`.

**Comment by amrgetment** [comment] 2024-02-22 17:12
@kevmoo Great in the future we will use Flutter as HTML 😂
HTML(
body: Column(children: [ImgElement(src:'url'), ])
)

😂😂😂

**Comment by srujzs** [comment] 2024-02-29 20:43
FYI - this is addressed in https://github.com/dart-lang/web/pull/185 and should be in the next version release.
