### ISSUE TITLE
window.navigator.share

### ISSUE THREAD

**Issue by woutervanwijk** [dart-lang/web#241] opened 2024-05-17 09:02 UTC
Small bug:
window.navigator.share is not supported in package:web, while it was in dart:html

**Comment by srujzs** [comment] 2024-05-20 20:12
Duplicate of https://github.com/dart-lang/web/issues/209

Should be added as part of https://github.com/dart-lang/web/pull/239.

**Closed** 2024-05-20 20:13 UTC
Labels: area-api-missing
